#!/usr/bin/env bash
# build_example.sh — stub illustrating how the build script is invoked
# during a cortex-agent-optimization SETUP or OPTIMIZE phase.
#
# In a real workspace this would be generated by setup/SKILL.md at Step 3.
# The actual script is created at: <WORKSPACE_ROOT>/scripts/build_agent_spec.py
#
# Usage (from workspace root):
#   python scripts/build_agent_spec.py
#   python scripts/build_agent_spec.py --dry-run
#   python scripts/build_agent_spec.py --json
#
# Flags:
#   (no flag)     Generate ALTER AGENT SQL → writes <AGENT_DIR>/deploy.sql
#   --dry-run     Print assembled spec to stdout without writing deploy.sql
#   --json        Output spec JSON only (for inspection)
#   --agent NAME  In multi-agent workspaces, target a specific agent dir

set -euo pipefail

WORKSPACE_ROOT="$(dirname "$0")/.."
AGENT_DIR="${WORKSPACE_ROOT}"
SCRIPTS_DIR="${WORKSPACE_ROOT}/scripts"

if [[ ! -f "${SCRIPTS_DIR}/build_agent_spec.py" ]]; then
    echo "ERROR: build_agent_spec.py not found at ${SCRIPTS_DIR}/"
    echo "Run the cortex-agent-optimization SETUP phase to generate it."
    exit 1
fi

# Dry run by default in this example stub
python "${SCRIPTS_DIR}/build_agent_spec.py" --dry-run
